### ISSUE TITLE
Image no longer available

### ISSUE THREAD

**Issue by NickLarsenNZ** [ministryofjustice/analytics-platform-concourse-ecr-repo-resource#1]
Hi,

I was hoping to use the resource. Is it no longer maintained?

_Also there's a typo in the Readme, fixed by_:
```diff
-     repository: quay.io.mojanalytics/concourse-ecr-resource
+     repository: quay.io/mojanalytics/concourse-ecr-resource
```
_...if the image could be pushed into Quay.IO_

**Comment by r4vi** [comment]
we've added a quay.io badge in the readme

**Comment by r4vi** [comment]
@NickLarsenNZ sorry we somehow missed this, yes it's still maintained, thanks for pointing out the typo in the README
